name: CD Admin

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy admin
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/learnary-admin:latest
            docker stop learnary_admin || true
            docker rm learnary_admin || true
            docker run -d --name learnary_admin -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/learnary-admin:latest
